version: '3'
services:
  jenkins:
    user: root
    image: jenkinsci/blueocean:latest
    ports:
     - "8180:8080"
     - "50000:50000"
    volumes:
     - ./jenkins-data:/var/jenkins_home
     - /var/run/docker.sock:/var/run/docker.sock
